### ISSUE TITLE
Distribuição geográfica das urnas antigas

### ISSUE THREAD

**Issue by cristianoherbert** [tonylampada/eleicoes22#3]
Tese: a diferença de votos entre urnas novas e urnas antigas é um indício de fraude
Antítese: existe algum outro fator (ex: sociológico) que explica a diferença de resultado entre os modelos de urnas
Hipótese: a diferença de resultados entre as urnas antigas e as novas se deve por uma questão geográfica

Análise 1: qual a distância de cada município com urna antiga para o município mais próximo com urna nova? (inspirado no método kkn de estatística)
- Distância 0 entre municípios, significando que o município possui urnas mistas, representa 7% da base (312/4569)
- A média da distância entre municípios é 89km
- Mediana de 60km
- Pareto de 145km (distância que abrange 80% dos casos)

Análise 2: qual a distância de cada município com urna antiga para a capital de sua UF?
- Distância 0 entre municípios, significando que o município é capital, representa 30% da base (8/27)
- A média da distância entre municípios é 275km
- Mediana de 256km
- Pareto de 406km (distância que abrange 80% dos casos)

[Cruzamento Municípios_Export.xlsx](https://github.com/tonylampada/eleicoes22/files/9980908/Cruzamento.Municipios_Export.xlsx)

>> Conclusão: ainda que de forma preliminar, a grande distância relativa entre os municípios é um indício que a distribuição geográfica entre os diferentes modelos de urnas pelo TSE foi não-aleatória, e portanto a análise de resultado por modelo de urnas apresenta um viés estatístico, e que não pode ser tratado de forma isolada

**Comment by cristianoherbert** [comment]
![image](https://user-images.githubusercontent.com/117913438/201099897-a0e34df5-6d74-4e03-9a1a-c4438fc7acc1.png)

**Comment by cristianoherbert** [comment]
![image](https://user-images.githubusercontent.com/117913438/201099931-07d39652-9b7f-4e96-96b9-43905a5e94fc.png)

**Comment by tonylampada** [comment]
Analise adicionada no readme!
