### ISSUE TITLE
Mais um repositório pra linkar

### ISSUE THREAD

**Issue by eusoubrasileiro** [tonylampada/eleicoes22#4]
Parabéns pelo excelente trabalho. 
Na mesma linha add ai depois na tua lista a minha brincadeira que chegou nas mesmas conclusões tuas. 

https://gitlab.com/sandbox279/tse_hell/-/blob/main/tse.ipynb

Parabéns mais uma vez

**Comment by tonylampada** [comment]
Analise adicionada no readme!
